Repository hanami/hanami.github.io, pull requests merged in 2021-06, with the labels that each got.

#526 New Git branches
  source/status.html.erb
Labels: enhancement

#528 New Git Branches
  source/blog/2021-06-18-new-git-branches.html.markdown
  source/blog/2021-06-18-new-git-branches/cover.jpg
Labels: announcement

#527 fixed typo
  source/blog/2021-05-04-announcing-hanami-200alpha2.html.markdown
Labels: fix
